name: YAMLLint
on:
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Lint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'clusters'
          yamllint_strict: false